name: FLAKE-LOCK_CI
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        run: nix flake update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(nix): update flake.lock"
          commit-message: "chore(nix): update flake.lock"
          branch: "nix/update-flake-lock"
          delete-branch: true
          body: |
            Automated update of the `flake.lock` file to keep Nix dependencies up to date.