name: MAIN_CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-vet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Check formatting
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "These files are not gofmt-formatted:"
            echo "$unformatted"
            exit 1
          fi

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            libgl1-mesa-dev \
            xorg-dev \
            gcc-mingw-w64-x86-64

      - name: Vet
        run: go vet ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Check project version
        run: bash ./scripts/set-version.sh --check

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            libgl1-mesa-dev \
            xorg-dev \
            gcc-mingw-w64-x86-64

      - name: Build with Script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
        env:
          ROCKPLOAD_VERSION: "dev"

      - name: Check generated files
        run: |
          ls -lh releases/
          [ "$(ls -A releases/)" ] || (echo "Error: No generated file" && exit 1)

  nix-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix flake validity
        run: nix flake check

      - name: Build project
        run: nix build .

      - name: Run Go tests
        run: nix develop --command go test ./...
