name: RELEASE_CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            libgl1-mesa-dev \
            xorg-dev \
            gcc-mingw-w64-x86-64

      - name: Build with Script
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          ROCKPLOAD_VERSION: ${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, '-pre') }}
          files: |
            releases/rockpload_*